"""Add Mission model and report features

Revision ID: 297f3bd1dff9
Revises: 467b75fdf390
Create Date: 2025-06-15 23:29:20.260862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297f3bd1dff9'
down_revision = '467b75fdf390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subject_target', sa.String(length=50), nullable=True),
    sa.Column('minutes_target', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission')
    # ### end Alembic commands ###
