"""Initial database structure

Revision ID: 61d2a64bba33
Revises: 
Create Date: 2025-06-16 09:12:09.682499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d2a64bba33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('week_start_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_name'], ['student.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('target_hour', sa.Integer(), nullable=True),
    sa.Column('target_min', sa.Integer(), nullable=True),
    sa.Column('actual_hour', sa.Integer(), nullable=True),
    sa.Column('actual_min', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_name'], ['student.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('mission')
    op.drop_table('student')
    # ### end Alembic commands ###
