"""Initial database structure with all final models

Revision ID: 76aa6255a233
Revises: 
Create Date: 2025-06-22 02:04:46.438849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76aa6255a233'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graded_pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_test', schema=None) as batch_op:
        batch_op.drop_column('graded_pdf_path')

    # ### end Alembic commands ###
