"""Add break_seconds to Todo model

Revision ID: b5c903f7f085
Revises: 61d2a64bba33
Create Date: 2025-06-18 12:12:52.122864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c903f7f085'
down_revision = '61d2a64bba33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_completions',
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.ForeignKeyConstraint(['student_name'], ['student.name'], ),
    sa.PrimaryKeyConstraint('student_name', 'mission_id')
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('break_seconds')

    op.drop_table('mission_completions')
    # ### end Alembic commands ###
